# File: _config.yml
remote_theme: hakimel/reveal.js
title: My Presentation Slides
description: A collection of presentation slides
baseurl: "/jekyll-with-reveal"  # Your repo name
url: "https://jvsocial.github.io"
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme

defaults:
  - scope:
      path: ""
    values:
      layout: reveal

      