remote_theme: hakimel/reveal.js
title: My Presentation Slides
description: A collection of presentation slides
baseurl: "/slides-presentation"  # Replace with your repo name
url: "" # Replace with your GitHub username
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme

defaults:
  - scope:
      path: ""
    values:
      layout: reveal